include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ImperiumAppleMusic
ImperiumAppleMusic_FILES = ImperiumAppleMusic.xm ../ImperiumClasses.m
ImperiumAppleMusic_FRAMWORKS = UIKit
ImperiumAppleMusic_PRIVATE_FRAMEWORKS = MediaRemote

include $(THEOS_MAKE_PATH)/tweak.mk
