ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = FlashNotifyApp
FlashNotifyApp_FILES = main.m
FlashNotifyApp_FRAMEWORKS = UIKit CoreGraphics
FlashNotifyApp_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/application.mk
