include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ImperiumSpotify
ImperiumSpotify_FILES = ImperiumSpotify.xm ../ImperiumClasses.m
ImperiumSpotify_FRAMWORKS = UIKit
ImperiumSpotify_PRIVATE_FRAMEWORKS = MediaRemote

include $(THEOS_MAKE_PATH)/tweak.mk
