include theos/makefiles/common.mk

BUNDLE_NAME = VolLockFS
VolLockFS_FILES = Switch.x
VolLockFS_FRAMEWORKS = UIKit
VolLockFS_LIBRARIES = flipswitch
VolLockFS_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk