include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = PhoneTabsCustomizerPrefs
PhoneTabsCustomizerPrefs_FILES = PTCRootListController.m PTCHeaderView.m
PhoneTabsCustomizerPrefs_INSTALL_PATH = /Library/PreferenceBundles
PhoneTabsCustomizerPrefs_FRAMEWORKS = UIKit
PhoneTabsCustomizerPrefs_PRIVATE_FRAMEWORKS = Preferences
PhoneTabsCustomizerPrefs_EXTRA_FRAMEWORKS = Cephei CepheiPrefs
PhoneTabsCustomizerPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
