include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ImperiumYoutube
ImperiumYoutube_FILES = ImperiumYoutube.xm ../ImperiumClasses.m
ImperiumYoutube_FRAMWORKS = UIKit
ImperiumYoutube_PRIVATE_FRAMEWORKS = MediaRemote

include $(THEOS_MAKE_PATH)/tweak.mk
